feat : 싱글방 문제세트를 싱글로 전송 [#27]
Sejong-GG/Sejong.GG pull request #42
Opened 2021-07-13 06:23 UTC by seoo890

- socket.js 에서 Chams로 크롤링된 모델을 담고,
- make로 서버에 문제셋 요청을 보내면 챔피언들 중 랜덤으로 하나를 골라 해당 챔피언의 content 4개를 quizSet 배열에 담은 후 get 통로를 이용해 해당 문제셋 전송 요청을 날림.
- 추후 기능이 모두 구현될 쯤에 randomtestIndex, randomIndex엔 랜덤 함수를 이용해 난수를 집어넣고 랜덤하게 선택 후 보낼 예정

Resolves #27

2021-07-13 07:44 UTC, kimhanui requested changes

2021-07-13 07:44 UTC, kimhanui commented on socket.js
> +    socket.on('make', ()=>//make 요청이 오면,
single 네임스페이스에 연결되자마자 퀴즈셋 전송해주는 코드도 추가해주실 수 있나요??

2021-07-14 02:55 UTC, seoo890 commented on socket.js
> +    socket.on('make', ()=>//make 요청이 오면,
수정했습니다

2021-07-14 03:36 UTC, cloud0406 approved these changes

2021-07-14 07:54 UTC, kimhanui requested changes

2021-07-14 07:54 UTC, kimhanui commented on socket.js
> +        socket.to(singleRoomId).emit('get', {quizSet, score})
socket -> single로 바꿔주세요

2021-07-14 07:54 UTC, kimhanui commented on socket.js
> +        return quizSet1[0];
quizSet1[0] -> quizSet1로 바꿔주세요

2021-07-14 07:54 UTC, kimhanui commented on socket.js
> +    socket.on('make', ()=>//make 요청이 오면,
@seoo890 음 이 코드 추가하니까 데이터 전송이 되던상황에서 전송이 안되네요. 
우선 PR https://github.com/Sejong-GG/Sejong.GG/pull/48 에서  클->서버로 make 이벤트 전송하게 했어요. 이 코드는 지우고 버그 나중에 수정해주세요!

2021-07-14 08:20 UTC, riyenas0925 approved these changes

2021-07-14 08:21 UTC, merged